# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet tool restore
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'dotnet tool restore'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: 'test'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/Coverage/'

- script: dotnet reportgenerator "-reports:$(Build.SourcesDirectory)/**/TestResults/Coverage/coverage.cobertura.xml" "-targetDir:$(Build.SourcesDirectory)/CodeCoverage" -reportTypes:Cobertura
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'dotnet reportgenerator'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/*cobertura.xml'
    failIfCoverageEmpty: false

- script: dotnet publish --no-build -c $(buildConfiguration)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'dotnet publish $(buildConfiguration)'

- task: DockerCompose@0
  displayName: 'docker compose build'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerhubConnection'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'

- task: DockerCompose@0
  displayName: 'docker compose push'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerhubConnection'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'push'

