# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: ".NET Build $(buildConfiguration)"
    inputs:
      command: "build"
      arguments: "-c $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: ".NET Tests"
    inputs:
      command: "test"

  - script: dotnet publish --no-build -c $(buildConfiguration)
    workingDirectory: $(Build.SourcesDirectory)
    displayName: '.NET Publish $(buildConfiguration)'

  - task: DockerCompose@0
    displayName: 'docker compose build'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerhubConnection'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'build'

  - task: DockerCompose@0
    displayName: 'docker compose push'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerhubConnection'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'push'

