version: '3.9'
services:
  microserviceapi1:
    container_name: microserviceapi1
    image: bolongdockerhub/microserviceapi1
    build:
      context: ./
      dockerfile: ./API1/Dockerfile
    ports:
      - 8081:80
  microserviceapi2:
    container_name: microserviceapi2
    image: bolongdockerhub/microserviceapi2
    build:
      context: ./
      dockerfile: ./API2/Dockerfile
    ports:
      - 8082:80
  microserviceapi3:
    container_name: microserviceapi3
    image: bolongdockerhub/microserviceapi3
    build:
      context: ./
      dockerfile: ./API3/Dockerfile
    ports:
      - 8083:80