version: '3.9'
services:
  microserviceapi1:
    container_name: microserviceapi1
    image: bolongdockerhub/microserviceapi1:v1.0.0
    build:
      context: ./
      dockerfile: ./API1/Dockerfile
    ports:
      - 8081:80
  microserviceapi2:
    container_name: microserviceapi2
    image: bolongdockerhub/microserviceapi2:v1.0.0
    build:
      context: ./
      dockerfile: ./API2/Dockerfile
    ports:
      - 8082:8082
  microserviceapi3:
    container_name: microserviceapi3
    image: bolongdockerhub/microserviceapi3:v1.0.0
    build:
      context: ./
      dockerfile: ./API3/Dockerfile
    ports:
      - 8083:80